theme: jekyll-theme-modernist
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: [Mineral_project site]
description: [This site aim to explain minerals and their description in two important knowledge graphs]
